baseURL = "https://tfada.fr/"
languageCode = "fr"
title = "tFada"
theme = "ananke"
SectionPagesMenu = "main"
googleAnalytics = "UA-55779894-1"
description = "Site perso sur l'actualit√© High Tech, Apple üë©‚Äçüíª, le d√©veloppement personnel."
preserveTaxonomyNames = true
disqusShortname: "tfada"
[permalinks]
  post = "/:title/"

[params]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/sebmouret"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  body_classes = "font"

